# This class stores the column data for each given csv into variables
class Data():
    def __init__(self):
        self.sim = []
        self.radiotype = []
        self.radio = []
        self.mcc = []
        self.mnc = []
        self.area = []
        self.cellid = []
        self.unit = []
        self.lat = []
        self.lon = []
        self.signal = []
        self.extra = []
        self.acc = []
        self.time = []
        self.speed = []
        self.bearing = []
        self.alt = []
        self.api = []
        self.device = []